"""
Centralised LangGraph state definitions for all workflows.

Design principle:
- Each workflow has its own TypedDict to avoid field collisions.
- Fields use Annotated reducers so LangGraph can safely merge parallel node updates.
- merge_dicts  → last-write-wins dict merge (safe for non-overlapping keys from parallel nodes)
- operator.add → list append (safe for parallel nodes adding to lists)
- All Optional fields default to None so nodes return only the fields they touch.
"""

from typing import TypedDict, List, Dict, Any, Optional, Annotated
import operator


def merge_dicts(a: Dict, b: Dict) -> Dict:
    """Merge two dicts, with b overriding a for shared keys."""
    return {**a, **b}


# ---------------------------------------------------------------------------
# WF1 — Story Topics
# Ends when topics are saved to Firestore and human picks a topic via API.
# ---------------------------------------------------------------------------
class StoryTopicsState(TypedDict):
    # Raw list of topic dicts generated by TopicsCreatorAgent.
    # None until first generation attempt.
    topics: Optional[List[dict]]

    # True once structural validation (required fields present) passes.
    # Separated from topics so we can distinguish "generated but invalid"
    # from "not yet generated".
    validated: bool

    # DeepEval GEval result: {"passed": bool, "score": float, "reason": str}
    # None until evaluation runs. Separated from validated because evaluation
    # is an expensive LLM call and may be skipped if structure validation fails.
    evaluation: Optional[dict]

    # How many times self_correction_agent has attempted to fix this output.
    # Capped at 2 to prevent infinite loops; after cap we propagate failure.
    correction_attempts: int

    # Populated by batch_create_stories_node after the full pipeline runs for
    # every topic. Maps title text → story_id (UUID).
    story_ids: Optional[Dict[str, str]]

    # LangGraph reducers — must use Annotated so parallel node updates are safe.
    completed: Annotated[List[str], operator.add]
    errors: Annotated[Dict[str, str], merge_dicts]


# ---------------------------------------------------------------------------
# WF2 — Story Creator
# Triggered after human selects a topic via POST /select-topic.
# ---------------------------------------------------------------------------
class StoryCreatorState(TypedDict):
    # Topic dict chosen by the human from WF1 output.
    # Passed in initial state when WF2 is triggered.
    selected_topic: Optional[dict]

    # Full story dict: {title, story_text, moral, age_group, language, metadata}
    story: Optional[dict]

    validated: bool

    # DeepEval evaluation result.
    evaluation: Optional[dict]

    correction_attempts: int
    completed: Annotated[List[str], operator.add]
    errors: Annotated[Dict[str, str], merge_dicts]


# ---------------------------------------------------------------------------
# WF3 — Image Generator (compiled subgraph, 4-retry internal)
# Uses FLUX.1-schnell via HuggingFace (same InferenceClient API as FLUX.1-dev).
# ---------------------------------------------------------------------------
class ImageWorkflowState(TypedDict):
    # Story content used to build the image generation prompt.
    story_text: str
    story_title: str

    # Raw PNG bytes from FLUX.1-schnell, or None if generation failed / not yet run.
    image_bytes: Optional[bytes]

    # GCS path after upload (e.g. "story-images/{uuid}.png").
    # This is what gets stored in Firestore — not the raw bytes.
    image_url: Optional[str]

    validated: bool
    evaluation: Optional[dict]

    # Internal retry counter (max 4 before returning needs_human status).
    retry_count: int

    # "completed" | "needs_human"
    status: str

    completed: Annotated[List[str], operator.add]
    errors: Annotated[Dict[str, str], merge_dicts]


# ---------------------------------------------------------------------------
# WF4 — Audio Generator (compiled subgraph, 4-retry internal)
# Uses Google Cloud Text-to-Speech API, single language per story.
# ---------------------------------------------------------------------------
class AudioWorkflowState(TypedDict):
    story_text: str

    # BCP-47 language code from config / request (e.g. "en-US", "ta-IN", "hi-IN").
    language: str

    # TTS voice name from config (e.g. "en-US-Standard-A").
    voice: str

    # Raw audio bytes (MP3) from TTS API.
    audio_bytes: Optional[bytes]

    # GCS path after upload (e.g. "story-audio/{uuid}.wav").
    audio_url: Optional[str]

    # Per-paragraph timing: [{ParagraphNumber, StartTimestamp, EndTimestamp, Duration}]
    audio_timepoints: Optional[List[dict]]

    validated: bool
    evaluation: Optional[dict]

    retry_count: int

    # "completed" | "needs_human"
    status: str

    completed: Annotated[List[str], operator.add]
    errors: Annotated[Dict[str, str], merge_dicts]


# ---------------------------------------------------------------------------
# WF5 — Activities (existing, now extended with 4-retry + DeepEval)
# Kept in activity_workflow.py but re-exported here for consistency.
# ---------------------------------------------------------------------------
class ActivityState(TypedDict):
    # Parallel activity outputs merged by merge_dicts reducer.
    activities: Annotated[Dict[str, Any], merge_dicts]
    images: Annotated[Dict[str, str], merge_dicts]
    completed: Annotated[List[str], operator.add]
    errors: Annotated[Dict[str, str], merge_dicts]
    retry_count: Annotated[Dict[str, int], merge_dicts]

    # Overall subgraph result status reported back to master.
    # "completed" | "needs_human"
    status: str


# ---------------------------------------------------------------------------
# Master Workflow State
# Coordinates WF1 (sequential) → WF2 (sequential) → WF3+WF4+WF5 (parallel).
# Request context (story_id, age, language) is passed read-only via
# config.configurable, NOT stored in state — following LangGraph best practice.
# ---------------------------------------------------------------------------
class MasterWorkflowState(TypedDict):
    # WHY story_id in state AND config:
    # config.configurable is for read-only inputs; state is for mutable outputs.
    # story_id here lets nodes log and route without digging into config.
    story_id: str

    # WF1 output — persisted so WF2 can be triggered separately after human picks.
    topics: Optional[List[dict]]

    # WF2 output — all downstream parallel workflows read from this.
    story: Optional[dict]

    # Per-workflow status: "pending" | "running" | "completed" | "failed" | "human_loop"
    # merge_dicts reducer lets each parallel subgraph update its own key safely.
    workflow_statuses: Annotated[Dict[str, str], merge_dicts]

    # Retry counter per parallel workflow (wf3/wf4/wf5).
    # Subgraphs manage their own internal retries (up to 4);
    # master uses this to decide on HITL escalation.
    workflow_retries: Annotated[Dict[str, int], merge_dicts]

    # Context stored when a workflow needs human intervention:
    # {"story_id": ..., "workflow_id": ..., "error": ..., "thread_id": ...}
    human_loop_requests: Annotated[Dict[str, dict], merge_dicts]

    # Human's decision per workflow, set via POST /resume-workflow:
    # "retry" | "skip" | "override"
    human_decisions: Annotated[Dict[str, str], merge_dicts]

    errors: Annotated[Dict[str, str], merge_dicts]
